"""
LinearRiskSharingPool: community-based insurance with allocation matrix.

Implements the linear risk-sharing framework from Denuit, Flores-Contró, and
Robert (2026), arXiv:2603.29530, "Linear Risk Sharing in Community-Based
Insurance."

The model
---------
Each participant i has a Cramér-Lundberg surplus process:

    U_i(t) = u_i + c_i * t - S_i(t)

where c_i = (1 + eta_i) * lambda_i * b_i is the premium rate, lambda_i is
claim intensity, b_i = E[Y_{i,1}] is mean claim size, and eta_i is the safety
loading. S_i(t) is a compound Poisson process with rate lambda_i.

Under the linear sharing rule with allocation matrix A = (a_{i,j}), participant
i absorbs fraction a_{i,j} of each claim generated by participant j. The pooled
surplus for participant i becomes:

    U_i^pool(t) = u_i + c_i * t - sum_j sum_{k: claim k from j} a_{i,j} * Y_{j,k}

Three matrix conditions are necessary (and sufficient under the scale family
assumption) to guarantee that pooling weakly reduces ruin probability for every
participant:

1. BUDGET BALANCE: sum_i a_{i,j} = 1 for all j (columns sum to 1)
2. ACTUARIAL FAIRNESS: lambda_i * b_i = sum_j a_{i,j} * lambda_j * b_j for all i
   (expected claim income unchanged per participant)
3. CAPACITY: a_{i,j} * b_j <= b_i for all i, j
   (no single transferred claim exceeds recipient capacity)

IMPORTANT: The theoretical guarantee (Proposition 3.8) requires a fourth
condition that cannot be checked by this class at construction time:
SCALE FAMILY — claim sizes must satisfy Y_{i,k} =^d b_i * W where W is a
common non-negative random variable with E[W] = 1. Exponential, Gamma with
fixed shape, and Lognormal with fixed sigma all satisfy this. Pareto does not
(unless normalised). Mixed severities do not. If your claim size distribution
does not belong to the same scale family across participants, the ruin
improvement guarantee does NOT hold.

IMPORTANT: The exact Cramér-Lundberg ruin formula (method='cramerlundberg')
is correct only for exponential severity. For any other distribution you must
use method='simulation'. Passing a non-exponential claim_dist with
method='cramerlundberg' raises ValueError.

Usage
-----
>>> import numpy as np
>>> from insurance_optimise import LinearRiskSharingPool

>>> pool = LinearRiskSharingPool.mean_proportional(
...     claim_intensities=np.array([2.0, 1.0, 3.0]),
...     claim_means=np.array([2.0, 0.5, 1.0]),
...     safety_loadings=np.array([0.4, 0.4, 0.4]),
... )
>>> result = pool.validate_conditions()
>>> print(result)
>>> ruin = pool.ruin_comparison()
>>> print(ruin.pooled)      # pooled ruin probabilities
>>> print(ruin.standalone)  # standalone ruin probabilities
>>> print(ruin.improvement) # positive means pooling helped

>>> sim = pool.simulate(T=50.0, n_paths=1000, seed=42)
>>> print(sim.empirical_ruin_probability)

>>> optimal = pool.optimal_allocation(objective='min_max_ruin')
>>> print(optimal.audit_trail())

References
----------
Denuit, M., Flores-Contró, J.M., Robert, C.Y. (2026). "Linear Risk Sharing
in Community-Based Insurance." arXiv:2603.29530.
"""

from __future__ import annotations

import datetime
import json
import warnings
from dataclasses import dataclass, field
from typing import Any

import numpy as np
from scipy.optimize import minimize


# ---------------------------------------------------------------------------
# PerformanceWarning
# ---------------------------------------------------------------------------

class PerformanceWarning(UserWarning):
    """Raised when a computation is likely to be slow or memory-intensive."""


# ---------------------------------------------------------------------------
# Result dataclasses
# ---------------------------------------------------------------------------


@dataclass
class ValidationResult:
    """
    Output from LinearRiskSharingPool.validate_conditions().

    Attributes
    ----------
    budget_balance_ok:
        True if sum_i a_{i,j} = 1 for all j (within tolerance).
    actuarial_fairness_ok:
        True if lambda_i * b_i = sum_j a_{i,j} * lambda_j * b_j for all i
        (within tolerance).
    capacity_ok:
        True if a_{i,j} * b_j <= b_i for all i, j (within tolerance).
    budget_balance_violations:
        Array of (column_sum - 1) for each j. Zero means satisfied.
    actuarial_fairness_violations:
        Array of (lhs - rhs) / (lambda_i * b_i) for each i (relative error).
        Zero means satisfied.
    capacity_violations:
        Maximum violation a_{i,j} * b_j - b_i across all i, j. Zero or
        negative means satisfied.
    all_ok:
        True if all three conditions are satisfied.

    Note
    ----
    This class cannot check the scale family condition — that is a property
    of the claim size distributions, not the allocation matrix. You must
    verify scale family membership separately.
    """

    budget_balance_ok: bool
    actuarial_fairness_ok: bool
    capacity_ok: bool
    budget_balance_violations: np.ndarray
    actuarial_fairness_violations: np.ndarray
    capacity_violations: float

    @property
    def all_ok(self) -> bool:
        """True if every matrix condition is satisfied."""
        return self.budget_balance_ok and self.actuarial_fairness_ok and self.capacity_ok

    def __repr__(self) -> str:
        status = "VALID" if self.all_ok else "INVALID"
        bb = "OK" if self.budget_balance_ok else f"FAIL (max={float(np.max(np.abs(self.budget_balance_violations))):.4f})"
        af = "OK" if self.actuarial_fairness_ok else f"FAIL (max_rel={float(np.max(np.abs(self.actuarial_fairness_violations))):.4f})"
        cap = "OK" if self.capacity_ok else f"FAIL (max={self.capacity_violations:.4f})"
        return (
            f"ValidationResult({status})\n"
            f"  budget_balance:      {bb}\n"
            f"  actuarial_fairness:  {af}\n"
            f"  capacity:            {cap}"
        )


@dataclass
class RuinResult:
    """
    Output from LinearRiskSharingPool.ruin_comparison().

    Attributes
    ----------
    pooled:
        Array of shape (n,). Infinite-time ruin probability for each
        participant under the pool.
    standalone:
        Array of shape (n,). Infinite-time ruin probability for each
        participant running independently (no sharing).
    improvement:
        standalone - pooled, elementwise. Positive values mean pooling
        reduced ruin probability for that participant.
    method:
        'cramerlundberg' for exact computation (exponential severity only)
        or 'simulation' for Monte Carlo estimate.
    """

    pooled: np.ndarray
    standalone: np.ndarray
    improvement: np.ndarray
    method: str
    initial_capital: np.ndarray

    def __repr__(self) -> str:
        improved = int(np.sum(self.improvement > 1e-10))
        n = len(self.pooled)
        return (
            f"RuinResult(method={self.method!r}, n={n}, "
            f"improved={improved}/{n}, "
            f"mean_improvement={float(np.mean(self.improvement)):.4f})"
        )


@dataclass
class SimulationResult:
    """
    Output from LinearRiskSharingPool.simulate().

    Attributes
    ----------
    empirical_ruin_probability:
        Array of shape (n,). Fraction of simulated paths in which each
        participant was ruined before time T.
    mean_ruin_time:
        Array of shape (n,). Mean ruin time across paths that experienced
        ruin. np.nan for participants with zero ruins.
    ruin_count:
        Array of shape (n, int). Number of paths (out of n_paths) in which
        each participant was ruined.
    n_paths:
        Number of simulated paths.
    T:
        Simulation horizon (years).
    claim_dist:
        Name of the claim size distribution used.
    n_participants:
        Number of participants in the pool.
    """

    empirical_ruin_probability: np.ndarray
    mean_ruin_time: np.ndarray
    ruin_count: np.ndarray
    n_paths: int
    T: float
    claim_dist: str
    n_participants: int

    def __repr__(self) -> str:
        improved = ""
        return (
            f"SimulationResult(n={self.n_participants}, T={self.T}, "
            f"n_paths={self.n_paths}, dist={self.claim_dist!r}, "
            f"mean_ruin_prob={float(np.mean(self.empirical_ruin_probability)):.4f})"
        )


# ---------------------------------------------------------------------------
# Cramér-Lundberg helpers
# ---------------------------------------------------------------------------


def _cl_ruin_exponential(
    lam: float,
    b: float,
    c: float,
    u: float,
) -> float:
    """
    Exact infinite-time ruin probability for a Cramér-Lundberg process
    with exponential claim sizes.

    The net profit condition requires c > lambda * b, i.e. safety loading
    eta > 0.

    Formula (Pollaczek-Khinchine for exponential):
        psi(u) = (lambda * b / c) * exp(-(c/b - lambda) * u / b)
              = rho * exp(-R * u)
    where rho = lambda * b / c and R = (c/b - lambda) / b = c/b^2 - lambda/b.

    For u=0:  psi(0) = lambda * b / c = 1 / (1 + eta).

    Parameters
    ----------
    lam : claim intensity (events per year)
    b   : mean claim size
    c   : premium rate (must satisfy c > lambda * b)
    u   : initial capital (must be >= 0)

    Returns
    -------
    float in [0, 1].
    """
    if c <= lam * b:
        # Net profit condition violated — certain ruin
        return 1.0
    rho = (lam * b) / c  # psi(0), in (0,1) when NPC holds
    R = (c - lam * b) / (b * c)  # Lundberg exponent  > 0
    return float(rho * np.exp(-R * u))


def _effective_pooled_process(
    i: int,
    allocation_matrix: np.ndarray,
    claim_intensities: np.ndarray,
    claim_means: np.ndarray,
    safety_loadings: np.ndarray,
) -> tuple[float, float, float]:
    """
    Compute effective (lambda_eff, b_eff, c_i) for participant i's pooled surplus.

    Under the scale family assumption (Y_{j,k} =^d b_j * W) with exponential W,
    participant i absorbs claims from all participants j weighted by a_{i,j}.
    The resulting claim process for i is a superposition of Poisson processes
    with intensities lambda_j and claim sizes a_{i,j} * Y_j. Each component
    a_{i,j} * Y_j is exponential with mean a_{i,j} * b_j.

    For a superposition of independent compound Poisson processes with
    exponential claims of possibly different means, the aggregate is NOT
    exponential in general. However, if all means happen to be equal, it is.

    This is the key restriction: the Cramér-Lundberg formula here applies
    under the HOMOGENEOUS SCALE FAMILY assumption where all a_{i,j} * b_j / b_i
    have the same scale (equivalently, the a_{i,j} are proportional to b_i / b_j).
    In practice, for the mean-proportional rule, this is approximately satisfied.

    We use the AGGREGATE first-two-moments approach: treat the pooled claim
    process as exponential with the same mean (this is exact for homogeneous
    exponential scale family, approximate otherwise). The user is warned via
    the docstring.

    Returns (lambda_eff, b_eff, c_i) where:
      lambda_eff = total rate of claims hitting participant i
      b_eff      = effective mean claim size per event
      c_i        = premium rate for participant i
    """
    n = len(claim_intensities)
    # Total expected claims per unit time hitting i
    expected_claims_i = float(
        np.sum(allocation_matrix[i, :] * claim_intensities * claim_means)
    )
    # Total event rate hitting i: only count sources where a_{i,j} > 0
    # (zero-allocation sources contribute nothing to i's surplus)
    active = allocation_matrix[i, :] > 1e-15
    lam_eff = float(np.sum(claim_intensities[active]))
    # Effective mean per event
    if lam_eff > 1e-15:
        b_eff = expected_claims_i / lam_eff
    else:
        b_eff = 0.0
    c_i = float(
        (1.0 + safety_loadings[i]) * claim_intensities[i] * claim_means[i]
    )
    return lam_eff, b_eff, c_i


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------


class LinearRiskSharingPool:
    """
    Linear risk-sharing pool for community-based insurance.

    Models n participants each with a Cramér-Lundberg surplus process.
    Claim costs are redistributed at claim time via a pre-specified n×n
    allocation matrix A = (a_{i,j}), where participant i absorbs fraction
    a_{i,j} of each claim generated by participant j.

    Reference: Denuit, Flores-Contró, Robert (2026), arXiv:2603.29530.

    SCALE FAMILY WARNING
    --------------------
    The theoretical guarantee that pooling reduces ruin probability
    (Proposition 3.8 of the paper) requires claim sizes to belong to a
    common scale family: Y_{i,k} =^d b_i * W for a shared non-negative W
    with E[W]=1. Exponential (shape=1 Gamma), Gamma with fixed shape, and
    Lognormal with fixed sigma all satisfy this. Pareto does not (in general).
    Mixed severity distributions across participants do not.

    If your data does not satisfy the scale family condition, the analytical
    ruin reduction guarantee does not apply. Use simulate() to check
    empirically.

    EXACT RUIN FORMULA
    ------------------
    The Cramér-Lundberg ruin probability formula (method='cramerlundberg')
    is exact only for exponential claim sizes. For any other distribution,
    use method='simulation'.
    """

    def __init__(
        self,
        allocation_matrix: np.ndarray,
        claim_intensities: np.ndarray,
        claim_means: np.ndarray,
        safety_loadings: np.ndarray,
        initial_capital: np.ndarray | None = None,
    ) -> None:
        """
        Construct a LinearRiskSharingPool directly from an allocation matrix.

        Parameters
        ----------
        allocation_matrix:
            (n, n) ndarray. Entry (i, j) is the fraction of participant j's
            claims absorbed by participant i. Columns should sum to 1
            (budget balance). Rows encode each participant's sharing rule.
        claim_intensities:
            Shape (n,). Poisson claim arrival rate lambda_i for each
            participant (claims per year).
        claim_means:
            Shape (n,). Mean claim size b_i = E[Y_{i,1}] for each participant.
        safety_loadings:
            Shape (n,). Safety loading eta_i for each participant. Premium
            rate is c_i = (1 + eta_i) * lambda_i * b_i. Must be > 0.
        initial_capital:
            Shape (n,). Initial surplus u_i for each participant. If None,
            defaults to 1.0 for all participants.

        Raises
        ------
        ValueError
            If any input has incompatible shape, or any safety loading is
            non-positive, or any intensity/mean is non-positive.
        """
        allocation_matrix = np.asarray(allocation_matrix, dtype=float)
        claim_intensities = np.asarray(claim_intensities, dtype=float)
        claim_means = np.asarray(claim_means, dtype=float)
        safety_loadings = np.asarray(safety_loadings, dtype=float)

        n = len(claim_intensities)

        if allocation_matrix.shape != (n, n):
            raise ValueError(
                f"allocation_matrix must be ({n}, {n}), "
                f"got {allocation_matrix.shape}"
            )
        if claim_means.shape != (n,):
            raise ValueError(f"claim_means must have shape ({n},), got {claim_means.shape}")
        if safety_loadings.shape != (n,):
            raise ValueError(f"safety_loadings must have shape ({n},), got {safety_loadings.shape}")
        if np.any(claim_intensities <= 0):
            raise ValueError("All claim_intensities must be positive.")
        if np.any(claim_means <= 0):
            raise ValueError("All claim_means must be positive.")
        if np.any(safety_loadings <= 0):
            raise ValueError(
                "All safety_loadings must be positive (eta_i > 0 is required "
                "for the net profit condition and finite ruin probability)."
            )
        if np.any(allocation_matrix < 0):
            raise ValueError("All allocation_matrix entries must be non-negative.")

        if initial_capital is None:
            initial_capital = np.ones(n)
        else:
            initial_capital = np.asarray(initial_capital, dtype=float)
            if initial_capital.shape != (n,):
                raise ValueError(
                    f"initial_capital must have shape ({n},), "
                    f"got {initial_capital.shape}"
                )
            if np.any(initial_capital < 0):
                raise ValueError("All initial_capital values must be non-negative.")

        self._A = allocation_matrix
        self._lambda = claim_intensities
        self._b = claim_means
        self._eta = safety_loadings
        self._u = initial_capital
        self._n = n

    @classmethod
    def mean_proportional(
        cls,
        claim_intensities: np.ndarray,
        claim_means: np.ndarray,
        safety_loadings: np.ndarray,
        initial_capital: np.ndarray | None = None,
    ) -> "LinearRiskSharingPool":
        """
        Construct a pool using the mean-proportional allocation rule.

        Under the mean-proportional rule, participant i's share of any
        participant j's claim is proportional to i's expected claim volume:

            a_{i,j}^np = lambda_i * b_i / sum_k (lambda_k * b_k)

        This rule gives every participant the same fraction of every loss,
        regardless of the loss source. It satisfies budget balance and
        actuarial fairness by construction. Capacity is not guaranteed —
        check with validate_conditions().

        The mean-proportional rule is the simplest and most auditable choice:
        allocation fractions are determined entirely by each participant's
        expected annual claim cost, which is easily observable and defensible
        to regulators.

        Parameters
        ----------
        claim_intensities:
            Shape (n,). Claim arrival rates.
        claim_means:
            Shape (n,). Mean claim sizes.
        safety_loadings:
            Shape (n,). Safety loadings eta_i > 0.
        initial_capital:
            Shape (n,) or None. If None, defaults to 1.0 per participant.

        Returns
        -------
        LinearRiskSharingPool
        """
        claim_intensities = np.asarray(claim_intensities, dtype=float)
        claim_means = np.asarray(claim_means, dtype=float)
        if np.any(claim_intensities <= 0):
            raise ValueError("All claim_intensities must be positive.")
        if np.any(claim_means <= 0):
            raise ValueError("All claim_means must be positive.")
        n = len(claim_intensities)
        volumes = claim_intensities * claim_means  # lambda_i * b_i
        total_volume = np.sum(volumes)
        if total_volume <= 0:
            raise ValueError("Total expected claim volume (sum lambda_i * b_i) must be positive.")
        shares = volumes / total_volume  # shape (n,)
        # Every column is the same (shares vector)
        A = np.outer(shares, np.ones(n))  # A[i,j] = shares[i] for all j
        return cls(
            allocation_matrix=A,
            claim_intensities=claim_intensities,
            claim_means=claim_means,
            safety_loadings=safety_loadings,
            initial_capital=initial_capital,
        )

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def n_participants(self) -> int:
        """Number of participants in the pool."""
        return self._n

    @property
    def allocation_matrix(self) -> np.ndarray:
        """The (n, n) allocation matrix A."""
        return self._A.copy()

    @property
    def claim_intensities(self) -> np.ndarray:
        """Claim intensities lambda_i, shape (n,)."""
        return self._lambda.copy()

    @property
    def claim_means(self) -> np.ndarray:
        """Mean claim sizes b_i, shape (n,)."""
        return self._b.copy()

    @property
    def safety_loadings(self) -> np.ndarray:
        """Safety loadings eta_i, shape (n,)."""
        return self._eta.copy()

    @property
    def initial_capital(self) -> np.ndarray:
        """Initial surplus u_i, shape (n,)."""
        return self._u.copy()

    @property
    def premium_rates(self) -> np.ndarray:
        """Premium rates c_i = (1 + eta_i) * lambda_i * b_i, shape (n,)."""
        return (1.0 + self._eta) * self._lambda * self._b

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def validate_conditions(self, tol: float = 1e-8) -> ValidationResult:
        """
        Check the three matrix conditions for ruin probability improvement.

        Checks:
          1. Budget balance: sum_i a_{i,j} = 1 for all j
          2. Actuarial fairness: lambda_i * b_i = sum_j a_{i,j} * lambda_j * b_j
          3. Capacity: a_{i,j} * b_j <= b_i for all i, j

        Does NOT check the scale family condition (distributional assumption).

        Parameters
        ----------
        tol:
            Absolute tolerance for budget balance and capacity checks.
            For actuarial fairness, relative tolerance (normalised by
            lambda_i * b_i).

        Returns
        -------
        ValidationResult
        """
        A = self._A
        lam = self._lambda
        b = self._b

        # 1. Budget balance: column sums
        col_sums = A.sum(axis=0)  # shape (n,)
        bb_violations = col_sums - 1.0
        budget_balance_ok = bool(np.all(np.abs(bb_violations) <= tol))

        # 2. Actuarial fairness
        # LHS: lambda_i * b_i for each i
        lhs = lam * b  # shape (n,)
        # RHS: sum_j a_{i,j} * lambda_j * b_j for each i
        rhs = A @ (lam * b)  # shape (n,)
        # Relative violations
        denominator = np.maximum(lhs, 1e-15)
        af_violations = (lhs - rhs) / denominator
        actuarial_fairness_ok = bool(np.all(np.abs(af_violations) <= tol))

        # 3. Capacity: a_{i,j} * b_j <= b_i
        # For each (i, j): A[i,j] * b[j] - b[i]
        # capacity_matrix[i,j] = A[i,j] * b[j] - b[i]
        capacity_matrix = A * b[np.newaxis, :] - b[:, np.newaxis]
        max_cap_violation = float(np.max(capacity_matrix))
        capacity_ok = bool(max_cap_violation <= tol)

        return ValidationResult(
            budget_balance_ok=budget_balance_ok,
            actuarial_fairness_ok=actuarial_fairness_ok,
            capacity_ok=capacity_ok,
            budget_balance_violations=bb_violations,
            actuarial_fairness_violations=af_violations,
            capacity_violations=max_cap_violation,
        )

    # ------------------------------------------------------------------
    # Ruin probabilities
    # ------------------------------------------------------------------

    def _ruin_probability_single(
        self,
        lam_eff: float,
        b_eff: float,
        c: float,
        u: float,
        method: str,
        n_sim: int,
        T: float | None,
        claim_dist: str,
        claim_dist_params: dict | None,
        rng: np.random.Generator,
    ) -> float:
        """Internal: compute ruin probability for one participant."""
        if method == "cramerlundberg":
            if claim_dist != "exponential":
                raise ValueError(
                    "method='cramerlundberg' is exact only for exponential severity. "
                    "For non-exponential distributions, use method='simulation'."
                )
            return _cl_ruin_exponential(lam_eff, b_eff, c, u)
        elif method == "simulation":
            return self._simulate_ruin_single(
                lam_eff, b_eff, c, u, n_sim, T, claim_dist, claim_dist_params, rng
            )
        else:
            raise ValueError(f"Unknown method {method!r}. Use 'cramerlundberg' or 'simulation'.")

    def _simulate_ruin_single(
        self,
        lam: float,
        b: float,
        c: float,
        u: float,
        n_sim: int,
        T: float | None,
        claim_dist: str,
        claim_dist_params: dict | None,
        rng: np.random.Generator,
    ) -> float:
        """Simulate ruin probability for a single surplus process."""
        if T is None:
            T = 200.0  # approximate infinite-time via long horizon
        params = claim_dist_params or {}
        ruin_count = 0
        for _ in range(n_sim):
            surplus = u
            t = 0.0
            ruined = False
            while t < T:
                dt_next = rng.exponential(1.0 / lam)
                t_next = t + dt_next
                if t_next > T:
                    break
                # Premium income up to next claim
                surplus += c * dt_next
                # Claim size
                claim = _draw_claim(b, claim_dist, params, rng)
                surplus -= claim
                t = t_next
                if surplus < 0:
                    ruined = True
                    break
            if ruined:
                ruin_count += 1
        return ruin_count / n_sim

    def ruin_comparison(
        self,
        method: str = "cramerlundberg",
        n_sim: int = 10_000,
        time_horizon: float | None = None,
        claim_dist: str = "exponential",
        claim_dist_params: dict | None = None,
        seed: int = 42,
    ) -> RuinResult:
        """
        Compare pooled vs standalone ruin probabilities for all participants.

        Exact for exponential severity (method='cramerlundberg'). For other
        distributions, use method='simulation'.

        Parameters
        ----------
        method:
            'cramerlundberg' — exact Pollaczek-Khinchine formula; requires
            claim_dist='exponential'.
            'simulation' — Monte Carlo estimate.
        n_sim:
            Number of simulation paths per participant. Used only for
            method='simulation'.
        time_horizon:
            Simulation horizon T in years. None means infinite-time
            approximation (T=200). Only used for method='simulation'.
        claim_dist:
            'exponential' or 'lognormal'. Only 'exponential' supports
            method='cramerlundberg'.
        claim_dist_params:
            Extra parameters for the claim distribution. For 'lognormal',
            pass {'sigma': value} (sigma of the log-normal, not the mean).
        seed:
            Random seed for reproducibility.

        Returns
        -------
        RuinResult
            .pooled — ruin probabilities under the pool (shape n)
            .standalone — ruin probabilities without pooling (shape n)
            .improvement — standalone - pooled (positive = pool helped)
            .method — 'cramerlundberg' or 'simulation'
        """
        if method == "cramerlundberg" and claim_dist != "exponential":
            raise ValueError(
                "method='cramerlundberg' requires claim_dist='exponential'. "
                "Use method='simulation' for other distributions."
            )

        rng = np.random.default_rng(seed)

        pooled_probs = np.empty(self._n)
        standalone_probs = np.empty(self._n)

        for i in range(self._n):
            # --- Standalone ---
            c_i = float((1.0 + self._eta[i]) * self._lambda[i] * self._b[i])
            standalone_probs[i] = self._ruin_probability_single(
                lam_eff=float(self._lambda[i]),
                b_eff=float(self._b[i]),
                c=c_i,
                u=float(self._u[i]),
                method=method,
                n_sim=n_sim,
                T=time_horizon,
                claim_dist=claim_dist,
                claim_dist_params=claim_dist_params,
                rng=rng,
            )

            # --- Pooled ---
            # Under scale family (exponential): the pooled process for
            # participant i is a superposition of compound Poisson processes.
            # Each participant j generates events at rate lambda_j; i absorbs
            # fraction a_{i,j} of each, giving effective claim size a_{i,j}*Y_j.
            # For method='cramerlundberg', we aggregate into a single effective
            # process using the aggregate mean (exact for homogeneous exponential
            # scale family by the memoryless / convolution property of exponential).
            lam_eff, b_eff, c_i = _effective_pooled_process(
                i, self._A, self._lambda, self._b, self._eta
            )
            pooled_probs[i] = self._ruin_probability_single(
                lam_eff=lam_eff,
                b_eff=b_eff,
                c=c_i,
                u=float(self._u[i]),
                method=method,
                n_sim=n_sim,
                T=time_horizon,
                claim_dist=claim_dist,
                claim_dist_params=claim_dist_params,
                rng=rng,
            )

        improvement = standalone_probs - pooled_probs

        return RuinResult(
            pooled=pooled_probs,
            standalone=standalone_probs,
            improvement=improvement,
            method=method,
            initial_capital=self._u.copy(),
        )

    # ------------------------------------------------------------------
    # Event-driven simulation
    # ------------------------------------------------------------------

    def simulate(
        self,
        T: float = 50.0,
        n_paths: int = 1000,
        claim_dist: str = "exponential",
        claim_dist_params: dict | None = None,
        seed: int = 42,
    ) -> SimulationResult:
        """
        Event-driven Monte Carlo simulation of the pool.

        Uses a Gillespie-style event-driven approach: inter-arrival times
        are drawn from Exponential(sum lambda_j), then the event is assigned
        to participant j with probability lambda_j / sum_k lambda_k. This is
        more efficient than per-participant simulation when n is small relative
        to expected event count.

        At each event for participant j, claim size Y_j is drawn and added
        to participant i's losses as a_{i,j} * Y_j.

        Parameters
        ----------
        T:
            Simulation horizon in years.
        n_paths:
            Number of independent Monte Carlo paths.
        claim_dist:
            'exponential' or 'lognormal'. Claim size distribution.
            All participants use the same family (scale family assumption).
        claim_dist_params:
            Extra distribution parameters. For 'lognormal', pass
            {'sigma': value}. If None, uses default sigma=1.0 for lognormal.
        seed:
            Random seed.

        Returns
        -------
        SimulationResult

        Warns
        -----
        PerformanceWarning
            When n_participants * n_paths * lambda_total * T > 1e7. The
            computation will still proceed but may be slow.
        """
        params = claim_dist_params or {}
        lam_total = float(np.sum(self._lambda))
        expected_events = n_paths * lam_total * T
        complexity = self._n * expected_events

        if complexity > 1e7:
            warnings.warn(
                f"High complexity: n_participants={self._n} * n_paths={n_paths} * "
                f"lambda_total={lam_total:.1f} * T={T} ≈ {complexity:.2e} operations. "
                "Simulation may be slow. Consider reducing n_paths or T.",
                PerformanceWarning,
                stacklevel=2,
            )

        rng = np.random.default_rng(seed)
        c = self.premium_rates  # shape (n,)

        # Accumulate results across paths
        ruin_flags = np.zeros((n_paths, self._n), dtype=bool)
        ruin_times_sum = np.zeros(self._n)

        # Pre-compute claim distribution probabilities for event assignment
        lam_probs = self._lambda / lam_total  # shape (n,), normalised

        for path in range(n_paths):
            surplus = self._u.copy()
            t = 0.0

            while t < T:
                # Time to next event from any participant
                dt = rng.exponential(1.0 / lam_total)
                t_next = t + dt
                if t_next > T:
                    # Accrue remaining premium, no more events
                    surplus += c * (T - t)
                    break

                # Premium income during dt
                surplus += c * dt
                t = t_next

                # Which participant generated this claim?
                j = int(rng.choice(self._n, p=lam_probs))

                # Draw claim size for participant j
                Y_j = _draw_claim(float(self._b[j]), claim_dist, params, rng)

                # Apply sharing: each participant i absorbs a_{i,j} * Y_j
                surplus -= self._A[:, j] * Y_j

                # Check for ruin
                ruined = surplus < 0.0
                if np.any(ruined) and not np.all(ruin_flags[path]):
                    newly_ruined = ruined & ~ruin_flags[path]
                    ruin_flags[path] |= newly_ruined
                    ruin_times_sum[newly_ruined] += t

                # If all participants ruined, stop early
                if np.all(ruin_flags[path]):
                    break

        ruin_count = ruin_flags.sum(axis=0)  # shape (n,)
        empirical_prob = ruin_count / n_paths

        with np.errstate(invalid="ignore"):
            mean_ruin_time = np.where(
                ruin_count > 0,
                ruin_times_sum / np.maximum(ruin_count, 1),
                np.nan,
            )

        return SimulationResult(
            empirical_ruin_probability=empirical_prob,
            mean_ruin_time=mean_ruin_time,
            ruin_count=ruin_count.astype(int),
            n_paths=n_paths,
            T=T,
            claim_dist=claim_dist,
            n_participants=self._n,
        )

    # ------------------------------------------------------------------
    # Optimal allocation
    # ------------------------------------------------------------------

    def optimal_allocation(
        self,
        objective: str = "min_max_ruin",
        capacity_slack: float = 0.0,
        fairness_tol: float = 1e-8,
    ) -> "LinearRiskSharingPool":
        """
        Optimise the allocation matrix via SLSQP.

        Finds the allocation matrix A that minimises (or maximises) the
        chosen objective, subject to budget balance and actuarial fairness
        as equality constraints, and capacity as inequality constraints.

        Parameters
        ----------
        objective:
            'min_max_ruin':
                Minimise the maximum ruin probability across participants
                (min-max criterion). Protects the worst-off participant.
            'max_min_improvement':
                Maximise the minimum ruin improvement across participants.
                Equivalent to min_max_ruin under the scale family.
        capacity_slack:
            Additional slack in capacity constraint. Setting > 0 relaxes
            capacity: a_{i,j} * b_j <= b_i + capacity_slack * b_j.
        fairness_tol:
            Tolerance for equality constraints in the SLSQP solver.

        Returns
        -------
        LinearRiskSharingPool
            A new pool instance with the optimised allocation matrix. The
            original pool is unchanged.

        Warns
        -----
        PerformanceWarning
            When n_participants > 30. SLSQP with n^2 free variables becomes
            slow for large n.

        Notes
        -----
        The optimisation treats all n^2 entries of A as free variables (not
        just the upper triangle), which allows asymmetric solutions. Budget
        balance is enforced as n equality constraints (column sums = 1).
        Actuarial fairness is enforced as n additional equality constraints.
        Capacity is enforced as n^2 inequality constraints. Non-negativity is
        enforced as bounds.
        """
        if self._n > 30:
            warnings.warn(
                f"optimal_allocation() with n_participants={self._n} is slow. "
                "SLSQP has n^2 variables. Consider n <= 30.",
                PerformanceWarning,
                stacklevel=2,
            )

        n = self._n
        lam = self._lambda
        b = self._b
        eta = self._eta

        # Variables: x = A.flatten(), shape (n*n,)
        x0 = self._A.flatten()

        def unpack(x: np.ndarray) -> np.ndarray:
            return x.reshape(n, n)

        def _ruin_probs(A: np.ndarray) -> np.ndarray:
            """Compute ruin probability for each participant given A."""
            probs = np.empty(n)
            for i in range(n):
                lam_eff_i = float(np.sum(lam))
                b_eff_i_num = float(np.dot(A[i, :], lam * b))
                b_eff_i = b_eff_i_num / lam_eff_i if lam_eff_i > 0 else 0.0
                c_i = float((1.0 + eta[i]) * lam[i] * b[i])
                probs[i] = _cl_ruin_exponential(lam_eff_i, b_eff_i, c_i, float(self._u[i]))
            return probs

        if objective == "min_max_ruin":
            def obj_fn(x: np.ndarray) -> float:
                A = unpack(x)
                return float(np.max(_ruin_probs(A)))
        elif objective == "max_min_improvement":
            # standalone probs are fixed
            standalone = np.array([
                _cl_ruin_exponential(
                    float(lam[i]),
                    float(b[i]),
                    float((1.0 + eta[i]) * lam[i] * b[i]),
                    float(self._u[i]),
                )
                for i in range(n)
            ])

            def obj_fn(x: np.ndarray) -> float:
                A = unpack(x)
                improvement = standalone - _ruin_probs(A)
                # Maximise min improvement = minimise -min improvement
                return float(-np.min(improvement))
        else:
            raise ValueError(
                f"Unknown objective {objective!r}. "
                "Use 'min_max_ruin' or 'max_min_improvement'."
            )

        # Constraints
        constraints = []

        # 1. Budget balance: sum_i A[i,j] = 1 for each j
        for j in range(n):
            def _bb_con(x: np.ndarray, j: int = j) -> float:
                A = unpack(x)
                return float(A[:, j].sum() - 1.0)
            constraints.append({"type": "eq", "fun": _bb_con})

        # 2. Actuarial fairness: lambda_i*b_i = sum_j A[i,j]*lambda_j*b_j
        lam_b = lam * b
        for i in range(n):
            def _af_con(x: np.ndarray, i: int = i) -> float:
                A = unpack(x)
                return float(np.dot(A[i, :], lam_b) - lam_b[i])
            constraints.append({"type": "eq", "fun": _af_con})

        # 3. Capacity: b_i - a_{i,j}*b_j + capacity_slack*b_j >= 0
        for i in range(n):
            for j in range(n):
                def _cap_con(x: np.ndarray, i: int = i, j: int = j) -> float:
                    A = unpack(x)
                    return float(b[i] - A[i, j] * b[j] + capacity_slack * b[j])
                constraints.append({"type": "ineq", "fun": _cap_con})

        # Bounds: 0 <= A[i,j] <= 1
        bounds = [(0.0, 1.0)] * (n * n)

        result = minimize(
            obj_fn,
            x0,
            method="SLSQP",
            bounds=bounds,
            constraints=constraints,
            options={"ftol": fairness_tol, "maxiter": 2000, "disp": False},
        )

        A_opt = unpack(result.x).clip(0.0, 1.0)

        return LinearRiskSharingPool(
            allocation_matrix=A_opt,
            claim_intensities=self._lambda.copy(),
            claim_means=self._b.copy(),
            safety_loadings=self._eta.copy(),
            initial_capital=self._u.copy(),
        )

    # ------------------------------------------------------------------
    # Audit trail
    # ------------------------------------------------------------------

    def audit_trail(self) -> dict[str, Any]:
        """
        Return a JSON-serialisable dict for FCA/regulatory documentation.

        The audit trail captures the full specification of the pool: all
        parameters, allocation matrix, and validation results. Consistent
        with the audit trail conventions used elsewhere in insurance-optimise.

        Returns
        -------
        dict
            JSON-serialisable audit record. Keys:
            - library, version, timestamp_utc
            - model_reference: paper citation
            - n_participants
            - parameters: intensities, means, loadings, capital, premiums
            - allocation_matrix: as nested list
            - validation: dict of condition results and violation magnitudes
            - scale_family_warning: reminder that this is not checked
        """
        from insurance_optimise import __version__

        ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
        val = self.validate_conditions()

        return {
            "library": "insurance-optimise",
            "version": __version__,
            "timestamp_utc": ts,
            "module": "risk_sharing.LinearRiskSharingPool",
            "model_reference": (
                "Denuit, Flores-Contró, Robert (2026). "
                "'Linear Risk Sharing in Community-Based Insurance.' "
                "arXiv:2603.29530."
            ),
            "n_participants": int(self._n),
            "parameters": {
                "claim_intensities": self._lambda.tolist(),
                "claim_means": self._b.tolist(),
                "safety_loadings": self._eta.tolist(),
                "initial_capital": self._u.tolist(),
                "premium_rates": self.premium_rates.tolist(),
            },
            "allocation_matrix": self._A.tolist(),
            "allocation_matrix_shape": list(self._A.shape),
            "validation": {
                "budget_balance_ok": bool(val.budget_balance_ok),
                "actuarial_fairness_ok": bool(val.actuarial_fairness_ok),
                "capacity_ok": bool(val.capacity_ok),
                "all_conditions_ok": bool(val.all_ok),
                "budget_balance_max_abs_violation": float(
                    np.max(np.abs(val.budget_balance_violations))
                ),
                "actuarial_fairness_max_rel_violation": float(
                    np.max(np.abs(val.actuarial_fairness_violations))
                ),
                "capacity_max_violation": float(val.capacity_violations),
            },
            "scale_family_warning": (
                "The ruin reduction guarantee requires scale family membership "
                "(Y_{i,k} =^d b_i * W, common W). This is NOT checked here. "
                "Verify that your severity distribution satisfies this condition."
            ),
        }

    def __repr__(self) -> str:
        val = self.validate_conditions()
        status = "VALID" if val.all_ok else "INVALID"
        return (
            f"LinearRiskSharingPool("
            f"n={self._n}, "
            f"conditions={status}, "
            f"lambda={self._lambda.round(2).tolist()}, "
            f"b={self._b.round(2).tolist()}, "
            f"eta={self._eta.round(2).tolist()}"
            f")"
        )


# ---------------------------------------------------------------------------
# Claim size helper
# ---------------------------------------------------------------------------


def _draw_claim(
    b: float,
    dist: str,
    params: dict,
    rng: np.random.Generator,
) -> float:
    """Draw a single claim size with mean b from the given distribution."""
    if dist == "exponential":
        return float(rng.exponential(b))
    elif dist == "lognormal":
        sigma = float(params.get("sigma", 1.0))
        # Lognormal with E[Y] = b: mu_ln = log(b) - sigma^2/2
        mu_ln = np.log(b) - 0.5 * sigma ** 2
        return float(rng.lognormal(mean=mu_ln, sigma=sigma))
    elif dist == "gamma":
        shape = float(params.get("shape", 1.0))
        scale = b / shape
        return float(rng.gamma(shape=shape, scale=scale))
    else:
        raise ValueError(
            f"Unknown claim distribution {dist!r}. "
            "Use 'exponential', 'lognormal', or 'gamma'."
        )
